# Generated by Django 5.2.8 on 2025-12-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organizationmember_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='deploy_tailscale',
            field=models.BooleanField(default=False),
        ),
    ]
