# Generated by Django 6.0 on 2025-12-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0003_organization_deploy_tailscale"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="enable_delegation",
            field=models.BooleanField(default=False),
        ),
    ]
