# Generated by Django 6.0 on 2025-12-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organization_enable_delegation'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='enable_cluster_access',
            field=models.BooleanField(default=False),
        ),
    ]
