apiVersion: 'karpenter.sh/v1'
kind: NodePool
metadata:
  annotations:
  labels:
    'pool.acme-ch.co': '{{ cluster.slug }}'
  name: '{{ cluster.slug }}'
spec:
  disruption:
    # allows up to 10% of notes to rotate during the 4 hours between (1000 UTC to 1400 UTC); and only one at a time otherwise.
    budgets:
      - nodes: '10%'
      - nodes: '1'
        duration: 20h
        reasons:
          - Underutilized
          - Empty
          - Drifted
        schedule: 0 14 * * * # https://crontab.guru/#0_8_*_*_*
    consolidateAfter: 5m
    consolidationPolicy: WhenEmptyOrUnderutilized
  limits:
    cpu: '12'
    memory: '64Gi'
  template:
    metadata:
      labels:
        pool.acme-ch.co: '{{ cluster.slug }}'
    spec:
      expireAfter: Never
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: '{{ cluster.slug }}'
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
        - key: node.kubernetes.io/instance-type
          operator: In
          values:
            - 't3a.medium'
        - key: topology.kubernetes.io/zone
          operator: In
          values:
            - '{{ region }}a'
            - '{{ region }}b'
            - '{{ region }}c'
        - key: pool.acme-ch.co
          operator: In
          values:
            - '{{ cluster.slug }}'
      taints:
        - effect: NoSchedule
          key: pool.acme-ch.co
          value: { { cluster.slug } }
