apiVersion: 'clickhouse.altinity.com/v1'
kind: 'ClickHouseInstallation'
metadata:
  name: 'clickhouse-installation'
  namespace: '{{ cluster.slug }}'
spec:
  configuration:
    clusters:
      - name: 'cluster'
        layout:
          replicasCount: 1
          shardsCount: 1
        templates:
          podTemplate: clickhouse-cluster
          serviceTemplate: clickhouse-cluster
    users:
      'defaultuser/networks/ip': '0.0.0.0/0'
      'defaultuser/password': "{{ cluster.id }}" # this is, after all, a demo
    settings:
      logger/console: true
      logger/level: information
      max_concurrent_queries: 2500
      prometheus/asynchronous_metrics: true
      prometheus/endpoint: /metrics
      prometheus/events: true
      prometheus/metrics: true
      prometheus/port: 9363
      prometheus/status_info: true
  defaults:
    templates:
      dataVolumeClaimTemplate: clickhouse-cluster
      serviceTemplate: clickhouse-cluster
  templates:
    podTemplates:
      - name: clickhouse-cluster
        spec:
          containers:
            - name: clickhouse
              image: '{{ server.image.repository }}:{{ server.image.tag }}'
              imagePullPolicy: IfNotPresent
              env:
                - name: CLICKHOUSE_ALWAYS_RUN_INITDB_SCRIPTS
                  value: 'true'
              volumeMounts:
                - mountPath: /var/lib/clickhouse
                  name: clickhouse-cluster
          nodeSelector:
            pool.acme-ch.co: '{{ cluster.slug }}'
          tolerations:
            - effect: NoSchedule
              key: pool.acme-ch.co
              operator: Equal
              value: '{{ cluster.slug }}'
          topologySpreadConstraints:
            - labelSelector:
                matchLabels:
                  clickhouse.altinity.com/chi: 'clickhouse-installation'
              maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: ScheduleAnyway
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchLabels:
                      clickhouse.altinity.com/chi: 'clickhouse-installation'
                  topologyKey: 'kubernetes.io/hostname'
    serviceTemplates:
      - name: clickhouse-cluster
        spec:
          ports:
            - name: http
              port: 8123
            - name: client
              port: 9000
    volumeClaimTemplates:
      - name: clickhouse-cluster
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: '20Gi'
          storageClassName: 'ebi'
