apiVersion: 'clickhouse-keeper.altinity.com/v1'
kind: 'ClickHouseKeeperInstallation'
metadata:
  name: 'clickhouse-keeper'
  namespace: '{{ cluster.slug }}'
spec:
  defaults:
    templates:
      podTemplate: clickhouse-keeper
      dataVolumeClaimTemplate: clickhouse-keeper
      serviceTemplate: clickhouse-keeper
  configuration:
    clusters:
      - name: chk-simple
        layout:
          replicasCount: 3
        templates:
          podTemplate: clickhouse-keeper
          dataVolumeClaimTemplate: clickhouse-keeper
          serviceTemplate: clickhouse-keeper
        settings:
          keeper_server/coordination_settings/raft_logs_level: information
          keeper_server/four_letter_word_white_list: '*'
          keeper_server/raft_configuration/server/port: '9444'
          keeper_server/storage_path: '/var/lib/clickhouse-keeper'
          keeper_server/tcp_port: '2181'
          listen_host: 0.0.0.0
          logger/console: 'true'
          logger/level: information
          prometheus/asynchronous_metrics: 'true'
          prometheus/endpoint: /metrics
          prometheus/events: 'true'
          prometheus/metrics: 'true'
          prometheus/port: '7000'
          prometheus/status_info: 'false'
  templates:
    podTemplates:
      - name: clickhouse-keeper
        spec:
          containers:
            - name: clickhouse-keeper
              image: '{{ keeper.image_repository }}:{{ keeper.image_tag }}'
              imagePullPolicy: IfNotPresent
          nodeSelector:
            'pool.acme-ch.co': 'clickhouse-keeper'
          tolerations:
            - effect: NoSchedule
              key: pool.acme-ch.co
              operator: Equal
              value: '{{ cluster.slug }}'
          topologySpreadConstraints:
            - maxSkew: 1
              minDomains: 3
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  'app': 'clickhouse-keeper'
          securityContext:
            fsGroup: 101
            runAsUser: 101
    serviceTemplates:
      - name: clickhouse-keeper
        metadata:
          namespace: clickhouse
        spec:
          ports:
            - name: tcp
              port: 2181
              targetPort: 2181
    volumeClaimTemplates:
      - name: clickhouse-keeper
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 12Gi
          storageClassName: ebi
